---

- name: set os-family specific variables
  include_vars: '{{ ansible_os_family  }}.yml'

- name: include nextcloud requirement installation
  become: yes
  include_tasks: "install_nextcloud_requirements_and_permissions.yml"
  when: nextcloud_install_requirements

- name: include redis installation and setup
  become: yes
  include_tasks: "setup_redis.yml"
  when: nextcloud_install_redis

- name: install and configure nginx
  become: yes
  include_tasks: "setup_nginx.yml"
  when: nextcloud_setup_nginx

- name: install and configure php
  become: yes
  include_tasks: "setup_php.yml"
  when: nextcloud_setup_php

- name: install and configure psqlite
  become: yes
  include_tasks: "setup_psqlite.yml"
  when: nextcloud_setup_sql and nc_db_type == 'pgsql' and nc_db_host == 'localhost')



