---

- name: set os-family specific variables
  include_vars: '{{ ansible_os_family  }}.yml'

- name: include nextcloud requirement installation
  become: yes
  include_tasks: "install_nextcloud_requirements_and_permissions.yml"
  when: nextcloud_install_requirements

- name: include redis installation and setup
  become: yes
  include_tasks: "setup_redis.yml"
  when: nextcloud_install_redis

- name: install and configure nginx
  become: yes
  include_tasks: "setup_nginx.yml"
  when: nextcloud_setup_nginx

- name: install and configure php
  become: yes
  include_tasks: "setup_php.yml"
  when: nextcloud_setup_php

- name: install and configure psqlite
  become: yes
  include_tasks: "setup_psql.yml"
  when: nextcloud_setup_sql and nc_db_type == 'pgsql' and nc_db_host == 'localhost'

- name: install and setup letsencrypt
  become: yes
  include_tasks: "setup_letsencrypt.yml"
  when: ssl_certificate_type == 'letsencrypt' and nextcloud_setup_tls 

- name: install and setup self-signed ssl
  become: yes
  include_tasks: "setup_tls.yml"
  when: ssl_certificate_type == 'selfsigned' and nextcloud_setup_tls 

- name: install and setup custom pre-generated tls
  become: yes
  include_tasks: "setup_custom_tls.yml"
  when: ssl_certificate_type == 'custom' and nextcloud_setup_tls 

- name: install nextcloud talk
  become: yes
  include_tasks: "setup_talk.yml"
  when: nextcloud_setup_talk and ansible_os_family != 'RedHat' 


