---

- name: install python-certbot-nginx
  become: yes
  package:
    name: "{{ nextcloud_python_certbot_nginx }}"
    state: present

- name: install acme pip package
  become: true
  pip:
    name: "{{ nextcloud_python_certbot_pip }}"
    state: latest
    executable: pip3

- name: ensure "{{ dhparam_path | dirname }}" exists
  become: true
  file:
    name:  "{{ dhparam_path | dirname }}"
    owner: root
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    mode:  0755
    state: directory

- name: create openssl dhparam (this may take a while)
  become: true
  openssl_dhparam:
    path: "{{ dhparam_path }}"
    size: "{{ dhparam_numbits | default(4096) }}"

- name: ensure nginx is stopped nginx
  become: true
  systemd:
    name: nginx
    state: stopped
    enabled: true

- name: install letsencrypt certificates
  become: true
  shell: "certbot certonly --standalone --installer nginx --email {{ cert_email }} --non-interactive --domain {{ fqdn }} --agree-tos {{ cert_stage|default('') }}"
  args:
    creates: /etc/letsencrypt/live/{{ fqdn }}/cert.pem

