---

- name: configure redis
  copy:
    src: redis.conf
    dest: "{{ redis_conf_path[ansible_os_family] }}/redis.conf"
    owner: root
    group: root
    mode: 0644
    force: true
  notify: restart redis-server

- name: add user {{ web_user[ansible_distribution] }} to group redis
  become: true
  user:
    name:   "{{ web_user[ansible_distribution] }}"
    groups: redis

- name: start and enable redis
  become: true
  systemd:
    name: redis
    state: started
    enabled: true

