---
- name: restart redis-server
  become: yes
  systemd:
    name: redis
    state: restarted

- name: restart nginx
  become: yes
  listen: enable coturn
  systemd:
    name: nginx
    state: restarted

- name: restart php-fpm
  become: yes
  systemd:
    name: "{{ php_service_name[ansible_os_family] }}"
    state: restarted

- name: restart collabora container
  become: yes
  shell: docker restart collabora_online

